.TH CHEESEMAKER 1 "7/7/2013" "Version 0.2.1" "User Commands"
.SH NAME
cheesemaker \- an image viewer
.SH SYNOPSIS
cheesemaker
.SH DESCRIPTION
Cheesemaker is a simple image viewer.
.SH SEE ALSO
https://github.com/riverrun/cheesemaker
.SH BUGS
No known bugs.
.SH AUTHOR
David Whitlock (alovedalongthe@gmail.com).
